### PR TITLE
upgrade backbone to 1.1.2

### PR DESCRIPTION
**Pull request by appleboy**
cc @arthurvr 

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

### CODE REVIEW

**Comment by appleboy** [comment]
ping @arthurvr

**Comment by arthurvr** [comment]
I'll review it shortly. Just didn't have the time yet.

**Comment by appleboy** [comment]
@arthurvr Thank you.

**Comment by arthurvr** [comment]
LGTM and perfectly working fine. Merging. Thanks @appleboy! :tada:

**Pull request closed without merging**
