### PR TITLE
Update Drag and Drop article and add a new post for proposed dropzone attr

### PR DESCRIPTION
**Pull request by stevendwood**
Shameless self promotion, but i recently spent months wrestling with the HTML5 drag and drop API on various browsers and ended up creating a polyfill for the [dropzone] attribute, as far as I can tell the only person foolish enough to bother with it.  There are a load of other fixes for various issues you can expect to face when using the dnd API for any non trivial use.  Feel free to take a look at my [stackoverflow] (http://stackoverflow.com/users/1906362/woody) (I was on here a lot asking about and answering questions on dnd) to see if you think my contributions are worthy of your fine site.

### CODE REVIEW

**Comment by arthurvr** [comment]
At the end, could you squash your commits? Thanks!

**Comment by arthurvr** [comment]
@stevendwood I reviewed it, and could you do some updates? Also If you'd like to update the hole drag and drop article on the while, feel free :beers:

**Comment by stevendwood** [comment]
@arthurvr - you raise a good point about it not being a polyfill for entire drag and drop API, but none of the others linked libraries are polyfills for the whole thing either.

I had a hard time actually coming up with a name for the project since there are many aspects to drag and drop.  Being able to drag any elements with the "draggable" attribute, being able to use the "dropzone" attribute and being able to customise the drag image. There's also the addition of "files" to the DataTransfer which is what the other polyfills seem to focus on.   I guess my library is attempting to be a polyfill for [dropzone] and a shim for other missing or broken things like DataTransfer.setDragImage and DataTransfer.setData("something other than text or URL on IE", "some value");  

Are there examples of other posts which mention useful libraries but not in the "polyfills" section ?

**Comment by arthurvr** [comment]
> I had a hard time actually coming up with a name for the project since there are many aspects to drag and drop. Being able to drag any elements with the "draggable" attribute, being able to use the "dropzone" attribute and being able to customise the drag image.

That's exactly why I'd like to seperate the drag n drop articles into different sections

**Comment by stevendwood** [comment]
@arthurvr Your comments seem to overlap so i am not exactly sure what you are proposing.  

What about new posts for the [draggable] and [dropzone] attributes (with appropriate more URLs) ?  For the draggable attribute post, the DataTransfer.setDragImage method and the is worth mentioning here I think.  What would the status be there ?  Since it works on IE10+ I would say "caution" because if you have a more complex case where you require a custom drag image, you'll need to use a shim like my library. 

For the dropzone attribute - what would the status be ?  As you point out there are not any implementations, however you could use my library as a polyfill.  Whether you would want to recommend using the dropzone attribute is not clear to me, since it's not clear whether it will ever get implemented natively.  So i think it has to be "avoid" however we could link to my library which gives a good idea of how the proposed attribute would work.

What would become of the existing drag and drop article ? It mainly deals with the ability to accept drops of files, so maybe it could be renamed to reflect this, or i could update it such that it's clearer that the polyfills are for the "drop file" use case ?  Let me know what you think.

**Comment by arthurvr** [comment]
> Let me know what you think.

Let's wait for some review from other team members. Personally I do think the dropzone and drag n drop articles must be splitted up, surely because I'd like to give them a different status. My opinion:

* Dropzone: avoid (with fallback/polyfill)
* drag n drop: use

**Comment by stevendwood** [comment]
Updated to add a dropzone post with status "avoid" and changed the status of drag and drop (and squashed the commits)...

**Comment by arthurvr** [comment]
@stevendwood Nice. I'il take a look at it later.

**Comment by stevendwood** [comment]
Oooops, my bad, so it does !  I should have checked that, I'll fix this up.

**Comment by stevendwood** [comment]
@arthurvr - I'm updating the drag and drop post to make it clearer where the "files" attribute will work natively.  I'm documenting the other main implementation inconsistencies (the DataTransfer setDragImage and set/getData methods).  Is there any standard way to indicate via the polyfill URL specificall what gaps they fill ? e.g. the current list will provide support for the missing "files" property on IE < 10, there are other polyfills out there that help get setDragImage and set/getData working, but none will polyfill all of the cracks....  I suppose we could list them all, usually the name will indicate what gap they address I suppose.

**Comment by stevendwood** [comment]
The article already contains that text, I didn't write it.  Peoples frustrations with the the drag and drop API are well documented.  [for example](http://www.quirksmode.org/blog/archives/2009/09/the_html5_drag.html)

**Comment by joeybaker** [comment]
FWIW, copy/pasting an article is plagiarism – only original copy please!

**Comment by stevendwood** [comment]
I don't understand.  I update an existing post on your site, retaining some of the text already in it, and you accuse me of plagiarism ??

**Comment by joeybaker** [comment]
@stevendwood oh, my mistake! I mistook you for saying that you took the text from the example article. I'm sorry.

**Comment by stevendwood** [comment]
Ah - no worries :)  yes the text @arthurvr is referring to is already in the drag and drop post on the html5please site today.  FWIW agree with the sentiment, the API is tough to use.

**Pull request closed without merging**
