### PR TITLE
Update browser support and misc text fixes

### PR DESCRIPTION
**Pull request by dstorey**
…details in each commit, but fixes outdated info such as recommending not to use the new gradient syntax, etc.

### CODE REVIEW

**Comment by mischah** [comment]
Thanks. This is huge.

@h5bp/html5please Could someone with admin rights restart that build? It should pass.

**Comment by alrra** [comment]
> Could someone with admin rights restart that build? 

@mischah Done! :)

**Comment by alrra** [comment]
Thanks @dstorey! :purple_heart:

**Comment by mischah** [comment]
:ok_hand:

**Pull request closed without merging**
