### PR TITLE
Update es6.md

### PR DESCRIPTION
**Pull request by yukulele**

### CODE REVIEW

**Comment by arthurvr** [comment]
Thanks for your PR, @yukulele. Only having Traceur in this list seems a little limited. I would like to see alternatives, [babel](https://github.com/babel/babel) for example, also there. Would you be willing to update your PR?

There is a separated issue about the ES6 post (https://github.com/h5bp/html5please/issues/342), it indeed needs quite a bunch of updates.

**Comment by arthurvr** [comment]
ping @yukulele

**Comment by paulirish** [comment]
Agree to mention babel.

we should link to the ES in 2015 page/video and mention jspm.

also we can nuke the last sentence and change "avoid" to "polyfill".

**Comment by arthurvr** [comment]
Merged :) :+1:

**Pull request closed without merging**
