### PR TITLE
added polyfill

### PR DESCRIPTION
**Pull request by mfranzke**

### CODE REVIEW

**Comment by mischah** [comment]
You kinda duplicated this one with #399

**Comment by mfranzke** [comment]
@mischah, thanks for your feedback. Could you please be a little bit more precise on your feelings?

**Comment by mischah** [comment]
Sure. 

- It looks misaligned.
- I understand that you choose a native select to store the options. But it looks like it doesn’t belong to the input field because it’s just another element.
  - Compare it to the native datalist or other polyfills.
- It doesn’t filter the data visibly while typing

That what comes to my mind spontaneously.

**Comment by mfranzke** [comment]
@mischah, thanks for following up on this.

I've actually compared it to any of the other solutions that I could have found on the web - and that's why I've build a new one actually, because the others either are dependent on too many libraries, wouldn't support dynamic HTML or other stuff like ARIA, or might just be deprecated.

Any other polyfill even also needs to use some other element if it's not supported natively - and both the W3C specs as well as others are using a select for their "simple" polyfills as well.

And a polyfill doesn't necessarily need to look exactly the same like the native UI elements, but provide you with the functionality. Studying the W3C specs, this polyfill does exactly what has been defined by the W3C specs, providing a list of options to the user to choose from, whereas a visible filtering of the options while typing isn't mentioned.
Please correct me if I'm wrong on this.

**Comment by mischah** [comment]
I totally feel your reasons for creating it 😘 

Adding a `multiple` attribute to the select makes it:
- look less like an alien element
- improves UX
  - filter the data visibly while typing

datalist

Then you just have to fix the alignment and I would gave it a 👍 
- same width like the input 
- same vertical position like the input

**Comment by framfr** [comment]
Thanks again for your thoughts and your feedback, that was very helpful ! 

I’ve previously decided against using the „multiple“ attribute, as I expected that it hurts the form follow function paradigm and behaves differently than expected (let’s you select more than one entry). But I overthought that and agree on the optimized general user experience.

Give it another try, please.

**Comment by mfranzke** [comment]
Thanks again for your thoughts and your feedback, that was very helpful !

I’ve previously decided against using the „multiple“ attribute, as I expected that it hurts the form follow function paradigm and behaves differently than expected (let’s you select more than one entry). But I overthought that and agree on the optimized general user experience.

Give it another try, please.

**Pull request closed without merging**
